name: Build and Publish Docker image
concurrency: build-${{ github.ref }}
on:
  push: 
    branches: [ main, mjw_test ]

permissions:
  contents: read
  packages: write
    
jobs:
  build-and-push-image:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        clean: true
        lfs: true
        submodules: true

    - name: Build and push
      working-directory: .
      run: |
        docker login -u $env:USER -p $env:TOKEN $env:REGISTRY
        docker build -t "pangaeatech/mssql-server-ltsc2022:latest" .
        docker image push "pangaeatech/mssql-server-ltsc2022:latest"
        docker logout
      env:
        REGISTRY: ghcr.io
        USER: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
