name: Build and Publish Docker image
concurrency: build-${{ github.ref }}
on:
  push: 
    branches: [ main, mjw_test ]

permissions:
  contents: read
  packages: write
    
jobs:
  build-and-push-image:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        clean: true
        lfs: true
        submodules: true

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: pangaeatech/mssql-server-ltsc2022:latest
          build-args: |
              'SQLCOLLATION=$Collation'
              'SHARE_PATH="\\$IP\Public"'
              'SHARE_PASSWORD="A.794613"'

